services:
  web:
    image: prakx/djangoblog:v1
    build: web/
    links:
      - postgres:postgres
    ports: 
      - "80:8000"
    environment:
      DB_USER: django_user
      DB_PASS: django_pass
      DB_NAME: django_db
      DB_HOST: postgres
    depends_on:
      - postgres
  postgres:
    image: postgres:14.10-alpine3.19
    restart: always
    volumes:
      - psqldb:/var/lib/postgresql
    environment:
      POSTGRES_USER: django_user
      POSTGRES_PASSWORD: django_pass
      POSTGRES_DB: django_db
  cli:
    image: prakx/blogdbcli:v1
    build: cli/
    links:
      - postgres:postgres
    volumes:
      - psqlcli:/dumps/
    environment:
      POSTGRES_USER: django_user
      POSTGRES_PASSWORD: django_pass
      POSTGRES_DB: django_db

volumes:
  psqldb:
  psqlcli:
